server:
  port: 8082
eureka:
  client:
    service-url:
      defaultZone: http://user:password123@localhost:8081/eureka/   #注册到其他的eureka机器上,如果有设置验证信息，不要忘了带上验证信息
spring:
  application:
    name: euraka_ha_server

info:    #添加actuator监控的端点信息，通过http://localhost:8080/info访问
  app:
    name: "spring_cloud_eureka_ha_server"
    encoding: "UTF-8"
    java:
      source: "1.8.0_171"
      target: "1.8.0_171"

security:  #为eureka server添加基于HTTP BASIC的安全认证
  basic:
    enabled: true
  user:
    name: user
    password: password123