server:
  port: 8058
spring:
  application:
    name: zuul_server
  cloud:
    config:
      server:
        git:
          # Git仓库地址
          uri: https://github.com/cocoyadi/spring-cloud-config.git
          # Git仓库账号
          username: 569424717@qq.com
          # Git仓库密码
          password: xiaoxun694686
          #对应配置文件中的profile
          profile: dev
          #git上的版本分支
          label: master